#!/system/bin/sh
file_chosen=$1
boot=$2
extsd=$(grep -i "/devices/platform/msm_sdcc.3/mmc_host/mmc2" /system/etc/vold.fstab | sed 's/dev_mount //g' | sed 's/ .*//g')
zimage=$(echo $file_chosen | sed "s/[/]//g" | sed -e "s/.*nar//" | sed "s/^/zimage_/" | sed -e "s|.zip||")
echo $file_chosen > /$extsd/lunar/lunardebug.log
md51=$(md5sum $file_chosen | cut -d ' ' -f 1)
md52=$(echo $file_chosen | sed -e "s|.zip|.md5|")
if [ -e $md52 ]; then
md52=$(cat $md52 | cut -d ' ' -f 1)
if [ "$md51" == "$md52" ]; then
echo "Zip MD5 Checksum matches" >> /$extsd/lunar/lunardebug.log
else
echo "MD5 checksum mismatch: Aborting script" >> /$extsd/lunar/lunardebug.log
exit
fi
fi
unzip -e -o $file_chosen lunarmenu/$zimage -d /data/local/tmp/ 2>> /$extsd/lunar/lunardebug.log
unzip -e -o $file_chosen kernel/zImage -d /data/local/tmp/ 2>> /$extsd/lunar/lunardebug.log
if [ -e /data/local/tmp/$zimage ]; then
mv /data/local/tmp/$zimage /data/local/tmp/chosen_zimage
fi
if [ -e /data/local/tmp/zImage ]; then
mv /data/local/tmp/zImage /data/local/tmp/chosen_zimage
fi
if [ ! -e /data/local/tmp/chosen_zimage ]; then
echo "Aborting script; is not a valid AnyKernel zip" >> /$extsd/lunar/lunardebug.log
exit
fi
sum1=$(sha1sum /data/local/tmp/chosen_zimage | cut -d ' ' -f 1)
mkdir /data/local/tmp/option3temp
dd if=/dev/block/$boot of=/data/local/tmp/option3temp/tempboot.img 2>> /$extsd/lunar/lunardebug.log
cd /data/local/tmp/option3temp
abootimg -x /data/local/tmp/option3temp/tempboot.img >> /$extsd/lunar/lunardebug.log
sum2=$(sha1sum /data/local/tmp/option3temp/zImage | cut -d ' ' -f 1)
cp /data/local/tmp/option3temp/tempboot.img /$extsd/lunar/boot_last_known_good.img
abootimg -u /data/local/tmp/option3temp/tempboot.img -k /data/local/tmp/chosen_zimage >> /$extsd/lunar/lunardebug.log
hexsize=$(printf "%x\n" $(($(wc -c < /data/local/tmp/chosen_zimage) + $(wc -c < /data/local/tmp/option3temp/initrd.img) + 6120)))
dd if=/data/local/tmp/option3temp/tempboot.img of=/dev/block/$boot 2>> /$extsd/lunar/lunardebug.log
dd if=/dev/block/$boot of=/data/local/tmp/option3temp/tempboot.img 2>> /$extsd/lunar/lunardebug.log
abootimg -x /data/local/tmp/option3temp/tempboot.img >> /$extsd/lunar/lunardebug.log
sed -i "s/bootsize.*/bootsize = 0x$hexsize/g" /data/local/tmp/option3temp/bootimg.cfg
abootimg -u /data/local/tmp/option3temp/tempboot.img -f /data/local/tmp/option3temp/bootimg.cfg
sum3=$(sha1sum /data/local/tmp/option3temp/zImage | cut -d ' ' -f 1)
if [ "$sum3" == "$sum1" ]; then
echo "flashed ok" >> /$extsd/lunar/lunardebug.log
cp /data/local/tmp/option3temp/tempboot.img /$extsd/lunar/boot_currentrom_chosenzip.img
rm /$extsd/lunar/boot_last_known_good.img
else
echo "flash unsuccessful" >> /$extsd/lunar/lunardebug.log
echo "restoring boot_last_known_good.img" >> /$extsd/lunar/lunardebug.log
dd if=/$extsd/lunar/boot_last_known_good.img of=/dev/block/$boot 2>> /$extsd/lunar/lunardebug.log
fi
rm /data/dalvik-cache/*
file_chosen=$(echo $file_chosen | sed -e "s|/$extsd/|/sdcard/|")
echo "--update_package=$file_chosen" > /cache/recovery/command
reboot recovery
