#!/system/bin/sh
mkdir recoverytemp
dd if=/dev/block/$recovery of=/$extsd/lunar/recoverytemp/recoverytemp.img 2>> lunardebug.log
cd recoverytemp
abootimg -x recoverytemp.img
recoverysize1=$(stat -c %s zImage)
recoverysize2=$(stat -c %s initrd.img)
recoverysize=$(($recoverysize1 + $recoverysize2 + 6120))
printf -v recoveryhexsize "%x" "$recoverysize"
sed -i "s/bootsize.*/bootsize = 0x$recoveryhexsize/g" bootimg.cfg
abootimg -u recoverytemp.img -f bootimg.cfg
cd ..
if [ ! -d "/$extsd/recovery_$DATE" ]; then
mkdir recovery_$DATE
fi
mv ./recoverytemp/recoverytemp.img ./recovery_$DATE/recovery.img
rm -r /$extsd/lunar/recoverytemp
