#!/system/bin/sh
cd /data/local/tmp
mkdir recoverytemp
dd if=/dev/block/$2 of=/data/local/tmp/recoverytemp/recoverytemp.img 2>> lunardebug.log
cd recoverytemp
abootimg -x recoverytemp.img
recoveryhexsize=$(printf "%x\n" $(($(wc -c < zImage) + $(wc -c < initrd.img) + 6120)))
sed -i "s/bootsize.*/bootsize = 0x$recoveryhexsize/g" bootimg.cfg
abootimg -u recoverytemp.img -f bootimg.cfg
cd /$extsd/lunar
if [ ! -d "/$extsd/recovery_$DATE" ]; then
mkdir recovery_$DATE
fi
mv /data/local/tmp/recoverytemp/recoverytemp.img ./recovery_$DATE/recovery.img
rm -r /$extsd/lunar/recoverytemp
