#!/system/bin/sh
if [ "$kerneltype" == "cmdline" ];then
if [[ $file_chosen == *.cfg ]]; then
dd if=/dev/block/$boot of=/$extsd/lunar/tempboot.img 2>> lunardebug.log
abootimg -x /$extsd/lunar/tempboot.img >> lunardebug.log
sed -i -e "s/gov.*//g" bootimg.cfg
file_chosen=$(cat $file_chosen)
sed -i -e "$ s/$/$file_chosen/g" bootimg.cfg
cat bootimg.cfg >> lunardebug.log
abootimg -u tempboot.img -f bootimg.cfg >> lunardebug.log
dd if=/$extsd/lunar/tempboot.img of=/dev/block/$boot 2>> lunardebug.log
rm bootimg.cfg
rm initrd.img
rm zImage
rm tempboot.img
fi
if [[ $file_chosen == *.img ]]; then
dd if=$file_chosen of=/dev/block/$boot 2>> lunardebug.log
fi
rm -r /data/dalvik-cache
echo "Rebooting to recovery....."
echo ".... to wipe Dalvik Cache & Cache"
echo "--wipe_cache" >> /cache/recovery/command
echo "GoodBye!"
reboot recovery
fi
if [ "$kerneltype" == "initd" ];then
gov=$(grep -i "gov=" $file_chosen | sed "s/ /\n/g" | sed "s/gov=//g" | head -n1 | tail -n1)
maxkhz=$(grep -i "maxkhz=" $file_chosen | sed "s/ /\n/g" | sed "s/maxkhz=//g" | head -n2 | tail -n1)
minkhz=$(grep -i "minkhz=" $file_chosen | sed "s/ /\n/g" | sed "s/minkhz=//g" | head -n3 | tail -n1)
scheduler=$(grep -i "scheduler=" $file_chosen | sed "s/ /\n/g" | sed "s/scheduler=//g" | head -n4 | tail -n1)
s2w=$(grep -i "s2w=" $file_chosen | sed "s/ /\n/g" | sed "s/s2w=//g" | tail -n1)
echo '#!/system/bin/sh' > /system/etc/init.d/99lunar
echo 'echo ''"'$scheduler'"' '> /sys/block/mmcblk0/queue/scheduler' >> /system/etc/init.d/99lunar
					echo 'echo "'$gov'" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_governor' >> /system/etc/init.d/99lunar
					echo 'echo "'$minkhz'" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq' >> /system/etc/init.d/99lunar
					echo 'echo "'$maxkhz'" > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq' >> /system/etc/init.d/99lunar
					if [ -d "/sys/devices/system/cpu/cpu1/" ]; then
					echo 'echo "'$gov'" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_governor' >> /system/etc/init.d/99lunar
					echo 'echo "'$minkhz'" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_min_freq' >> /system/etc/init.d/99lunar
					echo 'echo "'$maxkhz'" > /sys/devices/system/cpu/cpu1/cpufreq/scaling_max_freq' >> /system/etc/init.d/99lunar
					fi
					if [ -d "/sys/devices/system/cpu/cpu2/" ]; then
					echo 'echo "'$gov'" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor' >> /system/etc/init.d/99lunar
					echo 'echo "'$minkhz'" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq' >> /system/etc/init.d/99lunar
					echo 'echo "'$maxkhz'" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq' >> /system/etc/init.d/99lunar
					fi
					if [ -d "/sys/devices/system/cpu/cpu3/" ]; then
					echo 'echo "'$gov'" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_governor' >> /system/etc/init.d/99lunar
					echo 'echo "'$minkhz'" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_min_freq' >> /system/etc/init.d/99lunar
					echo 'echo "'$maxkhz'" > /sys/devices/system/cpu/cpu2/cpufreq/scaling_max_freq' >> /system/etc/init.d/99lunar
					fi
					if [ -e /sys/android_touch/sweep2wake ]; then
					echo 'echo '$s2w' > /sys/android_touch/sweep2wake' >> /system/etc/init.d/99lunar
					fi
					chmod 755 /system/etc/init.d/99lunar
					fi
					exit
