#!/system/bin/sh
extsd=$(grep -i "/devices/platform/msm_sdcc.3/mmc_host/mmc2" /system/etc/vold.fstab | sed 's/dev_mount //g' | sed 's/ .*//g')
dd if=$1 of=/dev/block/$2 2>> /$extsd/lunar/lunardebug.log
